Chapter: Architecture
apisyouwonthate/book-surviving-apis pull request #12
Opened 2019-09-08 16:27 UTC by philsturgeon

Closes #9.

This is a draft, and I need to add some reference links and whatnot. I'd also like to bolster the case for GraphQL beyond "meh IMO its daft" so I'd love your help there GQL fans. 

Also if the REST BFF stuff - or anything else - needs more splainin' please do point out what. But, bear in mind, this is the last chapter in a 12 chapter book, not a blog post. If something feels missing maybe its in a previous chapter. I can reference previously written stuff, but also maybe I forgot to reference it. This is what editors are for but y'all my editors. 😅

2019-09-09 02:16 UTC, cjunge-work requested changes

2019-09-09 02:16 UTC, cjunge-work commented on 12-architecture.adoc
> +This was due to some complex if statements checking 5 different things, and one of the apps forgot to check a 6th thing, so the state was out of whack. Hoisting these states up into the REST API mean
OAuth scopes

2019-09-09 13:01 UTC, tstuttard commented on 12-architecture.adoc
> +In the past I've worked at companies who used alternative mapping solutions which got bought out by some bigger company and immediately sunset. We had to pull a rush job to switch all mobile apps, we
> we could switch mapping providers more easily, and it end-users on mobile/desktop apps were not stuck with a broken experience until they upgraded.

to 

> we could switch mapping providers more easily, and it **meant** end-users on mobile/desktop apps were not stuck with a broken experience until they upgraded.

2019-09-14 03:06 UTC, notEthan commented on 12-architecture.adoc
> +_Chapter 9: Timeouts, Retries and Circuit Breakers_ covered a lot of the initial concerns with what can go wrong here. Mainly around remember to set timeouts in all client-side calls. Service mesh he
> Mainly around remember to set timeouts in all client-side calls.
grammar

2019-09-14 03:09 UTC, notEthan commented on 12-architecture.adoc
> +This is not always the case. Google Maps ditched their free mapping offering, Facebook regularly just turn off various APIs for whatever reason, and Meetup decided to ditch their API for any customer
```suggestion
This is not always the case. Google Maps ditched their free mapping offering, Facebook regularly just turns off various APIs for whatever reason, and Meetup decided to ditch their API for any customers who were not Pro. 
```

2019-09-14 03:10 UTC, notEthan commented on 12-architecture.adoc
> +In the past I've worked at companies who used alternative mapping solutions which got bought out by some bigger company and immediately sunset. We had to pull a rush job to switch all mobile apps, we
```suggestion
In the past I've worked at companies who used alternative mapping solutions which got bought out by some bigger company and immediately sunset. We had to pull a rush job to switch all mobile apps, web apps, and backend services over to Google Maps, and deploy them all. When we did we make a generic "mapping service" which would proxy requests to Google Maps in the background, meaning we could switch mapping providers more easily, and end-users on mobile/desktop apps were not stuck with a broken experience until they upgraded.
```

2019-09-14 03:14 UTC, notEthan commented on 12-architecture.adoc
> +A BFF is a chance for your team to optimize payloads, by grabbing these larger chunks of data and returning only what thinks you probably need.
not sure if this is supposed to be 'returning only what it [the BFF] thinks you probably need' or 'returning only what things you probably need'

2019-09-14 03:17 UTC, notEthan commented on 12-architecture.adoc
> +In the past I've worked at companies who used alternative mapping solutions which got bought out by some bigger company and immediately sunset. We had to pull a rush job to switch all mobile apps, we
removed 'it' from the last sentence

2019-09-14 03:19 UTC, notEthan commented on 12-architecture.adoc
> +BFFs also let you solve authentication inconsistencies between the various APIs a client needs to talk to, by letting the end user authenticate with your BFF, then it creates various JWTs, bearer tok
maybe worth mentioning that often the client should not even have access to direct calls to dependent APIs; the authentication for those may be higher privilege than clients should have.

2019-09-17 14:19 UTC, philsturgeon commented on 12-architecture.adoc
> +A more lightweight debugging/tracing proxy like https://httptoolkit.tech/[HTTP Toolkit] if you need more insight into what is going on if a service mesh is out of reach, but relying on logs alone is
Hey could you do me a solid and use the Suggestion button? It's easier for both of us :D 
<img width="119" alt="image" src="https://user-images.githubusercontent.com/67381/65049954-a027cb00-d934-11e9-982e-922d0a3cae86.png">

2019-10-07 20:06 UTC, merged